### ISSUE TITLE
Add food ratings 

### ISSUE THREAD

**Issue by Robert27** [neuland-ingolstadt/neuland.app-backend#5]
The user should be able to rate the canteen food in the Neuland App and see the respective average rating. In addition it should also be possible to report wrong dishes.
Since the dishes are usually repeated every few weeks, we can make use of it and keep a history of ratings per meal.

Some problems that need to be clarified beforehand are:

- [ ] How can we make sure that each person only votes once and doesn't spam the API to manipulate the review?
- [ ] How to design the database schema and backend logic?
- [ ] What data protection changes are accompanied by this?
- [ ] Can a user vote again if the dish is served again after a few weeks?

The following backend steps must be completed:
- [ ] Update the database with the designed scheme
- [ ] Extend backend logic to store and re-identify dishes
- [ ] “Authentication” to avoid multiple reviews
- [ ] Create new queries and mutations to evaluate dishes
